### ISSUE TITLE
packages on Fedora

### ISSUE THREAD

**Issue by prk3** [domschrei/krunner-symbols#14]
Hi! This is a list of packages I had to install on fedora 29 in order to compile krunner-symbols. It's most definitely not complete, but maybe it will get some people closer to a working plugin. :)
```
sudo dnf install cmake extra-cmake-modules kf5-ki18n-devel kf5-kservice-devel kf5-krunner-devel kf5-ktextwidgets-devel gettext
```

**Comment by domschrei** [comment]
Thanks a lot! I added it to the Readme.

**Comment by paul** [comment]
On Fedora 30, I had to add `qt5-qtdeclarative-devel`.
