### ISSUE TITLE
Upcoming krunner store

### ISSUE THREAD

**Issue by torbei** [domschrei/krunner-symbols#17]
Apparently there is a krunner store in the making, which makes installing krunner extensions easier:
https://www.reddit.com/r/kde/comments/h8fjyr/coming_soon_krunner_store_this_shows_how_you_can/

This might make the installation easier for some people and might help gain more interest in the extension.
We should keep an eye onto that.

**Comment by domschrei** [comment]
For now I am happy to announce that the plugin found its way into the KDE store :)
See: https://store.kde.org/p/1419376/
Not sure if (and how) we should still pursue #15 anyway.
