### ISSUE TITLE
Multiple keywords for key

### ISSUE THREAD

**Issue by torbei** [domschrei/krunner-symbols#6]
Would be great if there is a way to define multiple keywords for a key instead of creating multiple keys with the same value.

**Comment by domschrei** [comment]
You now have the option to write something like this into your custom definitions:
```
ampersand,fancyand,curlyand=&
```
which will be internally expanded to:
```
ampersand=&
fancyand=&
curlyand=&
```
The amount of keywords on the left side (>= 2) is arbitrary. Note that this feature disables the use of commata inside symbol definition keywords apart from multi-definitions.
