### ISSUE TITLE
Can we somehow integerate it with CopyQ?

### ISSUE THREAD

**Issue by hemantcompiler** [domschrei/krunner-symbols#7]
Like when searching in the clipboard history in copyQ, the saved items appears first? Can it be used like pinning items in the clipboard, like the native clipboard app in android?

**Comment by domschrei** [comment]
I don't really understand yet what you'd like to do. Could you provide an example?

I haven't used CopyQ yet, but I installed it and am going to try it out.  As of now, when you trigger the action of one of the plugin's symbols (i.e. you press enter), it will be copied to the default clipboard and also appears in the CopyQ UI.
